#include <cstdio>
#include <iostream>
#include <algorithm>
#include <vector>

using namespace std;

const int N = 100000;
int n;
vector <int> a, mina, maxa;

void find_max (bool mi , vector <int> &s){
    vector <int> b;
    for (int i = 0;  i < n; ++i) b.push_back(0)
    if (mi) for (int i = 0; i < n; i++)
    {
        int k = lower_bound(b.begin)
    }
    
}

void start (){
    cin >> n;
    int x;
    for (int i = 1; i <= 0){
        cin >> x;
        a.push_back (x);
        mina.push_back (N + 1);
        maxa.push_back (0);
    }
}
int main (){
    freopen ("SPSEQ.INP", "r", stdin);
    freopen ("SPSEQ.OUT", "w", stdout);

}